### ISSUE TITLE
Remove dependency on Zstd (from ZipWriter) for easier wasm setup

### ISSUE THREAD

**Issue by rRaDuCaN** [jmcnamara/rust_xlsxwriter#11]
Provide a lighter version of the lib without any c lib dependencies, for a possibly, web assembly integration. Zstd is driving me crazy with wasm setup.

**Comment by jmcnamara** [comment]
I've pushed a change to main to reduce the zipwriter dependencies down to just "defalate" and effectively removing the "zstd" dependency. Can you try that and let me know how you get on.

**Comment by jmcnamara** [comment]
And just in case it isn't clear you can test it by changing your dependency to this:

```toml
[dependencies]
rust_xlsxwriter = { git = "https://github.com/jmcnamara/rust_xlsxwriter" }
```
